openapi: 3.1.0
info:
  description: Example API
  title: My API
  version: 1.0.0
servers:
- url: https://api.example.com
paths:
  /api/v1/auth/login:
    post:
      description: User Login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseMainToken'
          description: OK
      summary: User Login
      tags:
      - Authentication
  /api/v1/auth/me:
    get:
      description: Get Profile
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseMainUser'
          description: OK
      security:
      - bearerAuth: []
      summary: Get Profile
      tags:
      - Authentication
components:
  schemas:
    LoginRequest:
      properties:
        password:
          type: string
        username:
          type: string
      required:
      - username
      - password
      type: object
    ResponseMainToken:
      properties:
        data:
          $ref: '#/components/schemas/Token'
        status:
          type: integer
      type: object
    ResponseMainUser:
      properties:
        data:
          $ref: '#/components/schemas/User'
        status:
          type: integer
      type: object
    Token:
      properties:
        access_token:
          type: string
      type: object
    User:
      properties:
        id:
          type: string
        name:
          type: string
      type: object
  securitySchemes:
    bearerAuth:
      scheme: Bearer
      type: http
